
package com.humber.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateInterestImplService", targetNamespace = "http://service.humber.com/", wsdlLocation = "http://localhost:8080/endpoint/soapHandler?wsdl")
@HandlerChain(file="../handler/handler-chain.xml")
public class CalculateInterestImplService
    extends Service
{

    private final static URL CALCULATEINTERESTIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATEINTERESTIMPLSERVICE_EXCEPTION;
    private final static QName CALCULATEINTERESTIMPLSERVICE_QNAME = new QName("http://service.humber.com/", "CalculateInterestImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/endpoint/soapHandler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATEINTERESTIMPLSERVICE_WSDL_LOCATION = url;
        CALCULATEINTERESTIMPLSERVICE_EXCEPTION = e;
    }

    public CalculateInterestImplService() {
        super(__getWsdlLocation(), CALCULATEINTERESTIMPLSERVICE_QNAME);
    }

    public CalculateInterestImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATEINTERESTIMPLSERVICE_QNAME, features);
    }

    public CalculateInterestImplService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATEINTERESTIMPLSERVICE_QNAME);
    }

    public CalculateInterestImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATEINTERESTIMPLSERVICE_QNAME, features);
    }

    public CalculateInterestImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateInterestImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculateInterest
     */
    @WebEndpoint(name = "CalculateInterestImplPort")
    public CalculateInterest getCalculateInterestImplPort() {
        return super.getPort(new QName("http://service.humber.com/", "CalculateInterestImplPort"), CalculateInterest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculateInterest
     */
    @WebEndpoint(name = "CalculateInterestImplPort")
    public CalculateInterest getCalculateInterestImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.humber.com/", "CalculateInterestImplPort"), CalculateInterest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATEINTERESTIMPLSERVICE_EXCEPTION!= null) {
            throw CALCULATEINTERESTIMPLSERVICE_EXCEPTION;
        }
        return CALCULATEINTERESTIMPLSERVICE_WSDL_LOCATION;
    }

}
