
package com.humber.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculateInterest", targetNamespace = "http://service.humber.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculateInterest {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInterest", targetNamespace = "http://service.humber.com/", className = "com.humber.service.GetInterest")
    @ResponseWrapper(localName = "getInterestResponse", targetNamespace = "http://service.humber.com/", className = "com.humber.service.GetInterestResponse")
    @Action(input = "http://service.humber.com/CalculateInterest/getInterestRequest", output = "http://service.humber.com/CalculateInterest/getInterestResponse")
    public double getInterest(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
